version: '3.8'

services:
  python_standalone:
    container_name: python_standalone  
    build: .
    tty: true
    ports:
      - "5000:5000"
    restart: unless-stopped  
    volumes:
      - .:/src/apps

